[env]
TERM = "xterm-256color"

[window]
padding = { x = 7, y = 26 }
decorations = "transparent"
option_as_alt = "Both"

[font]
size = 15.0
normal = { family = "FiraCode Nerd Font Mono" }

[colors]
primary.background = "#000000"

[selection]
save_to_clipboard = true

[hints]
[[hints.enabled]]
action = "Select"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Command|Option|Alt" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
  { key = "Left", mods = "Option", chars = "\u001BB" },
  { key = "Right", mods = "Option", chars = "\u001BF" },
]
