gui:
  sidePanelWidth: 0.25
  showDivergenceFromBaseBranch: arrowAndNumber
  mouseEvents: false
  showBottomLine: false
  showIcons: true
  nerdFontsVersion: "3"
  branchColors:
    "feat": "#51bf37"
    "feature": "#51bf37"
    "fix": "#b83019"
    "poc": "#53c2c5"
git:
  autoFetch: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  mainBranches:
    - master
    - main
    - develop
    - dev/S27
  refresher:
    fetchInterval: 60
os:
  editPreset: "nvim"
confirmOnQuit: true
notARepository: skip
